base_url = "https://blog.8192000.xyz/"
compile_sass = true
build_search_index = true
title = "nekrozis's Blog"
description = "A personal lab: documenting practice and shaping code."

generate_feeds = true

theme = "linkita"

[link_checker]
skip_prefixes = ["https://blog.8192000.xyz"]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[[taxonomies]]
name = "categories"
feed = true
paginate_by = 5

[[taxonomies]]
name = "tags"
feed = true
paginate_by = 4

[[taxonomies]]
name = "authors"
feed = true
paginate_by = 4

[extra]
author = "nekrozis"
math = true
mermaid = true
comment = false
header_menu_name = "main_menu"
date_format = "%B %e, %Y"
use_cdn = true

[extra.footer]
since = 2024
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed.zh"
copyright = "&copy; $YEAR Hs√º Ching | [CC BY-SA 4.0]($LICENSE_URL)"

[extra.menus]
main_menu = [
  { url = "$BASE_URL/archive/", name = "Archive" },
  { url = "$BASE_URL/categories/", name = "Categories" },
  { url = "$BASE_URL/tags/", name = "Tags" },
  { url = "$BASE_URL/about/", name = "About" },
]

[extra.profiles.nekrozis]
name = "nekrozis"
bio = "The understanding does not derive its laws from nature, but imposes them upon it."
avatar_url = "/avatar.png"
avatar_alt = "nekrozis profile avatar"

social = [
    { name = "github", url = "https://github.com/nekrozis" },
    { name = "email", url = "mailto:mgal25@outlook.com" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]
